name: LATU GPT-Claude Analysis Pipeline
on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [analysis-request]

jobs:
  gpt-first-analysis:
    runs-on: ubuntu-latest
    if: github.event.client_payload.stage == 'gpt-first'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install openai requests
      
      - name: Run GPT First Analysis
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          python scripts/gpt_analysis.py \
            --symbol "${{ github.event.client_payload.symbol }}" \
            --price "${{ github.event.client_payload.price }}" \
            --change "${{ github.event.client_payload.change }}" \
            --volume "${{ github.event.client_payload.volume }}" \
            --webhook-url "${{ github.event.client_payload.webhook_url }}"

  claude-detailed-analysis:
    runs-on: ubuntu-latest
    if: github.event.client_payload.stage == 'claude-detailed'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install anthropic requests
      
      - name: Run Claude Detailed Analysis
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          python scripts/claude_analysis.py \
            --symbol "${{ github.event.client_payload.symbol }}" \
            --gpt-result "${{ github.event.client_payload.gpt_result }}" \
            --webhook-url "${{ github.event.client_payload.webhook_url }}"

  final-comparison:
    runs-on: ubuntu-latest
    if: github.event.client_payload.stage == 'final-comparison'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install openai requests
      
      - name: Run Final Comparison
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          python scripts/final_comparison.py \
            --symbol "${{ github.event.client_payload.symbol }}" \
            --gpt-result "${{ github.event.client_payload.gpt_result }}" \
            --claude-result "${{ github.event.client_payload.claude_result }}" \
            --webhook-url "${{ github.event.client_payload.webhook_url }}"
